[plugins]
gradle-publish = { id = "com.gradle.plugin-publish", version = "1.0.0" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "1.7.21" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "11.0.0" }
